- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/bin

- link:
    ~/bin/bat:
      force: true
      path: bin/bat-linux
    ~/bin/exa:
      force: true
      path: bin/exa-linux
    ~/.zshrc:
      force: true
      path: zsh/zshrc

- npm:
    - rimraf
    - npm-check

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    -
      command: sh ./npm/set-defaults.sh
      description: Setting up sane npm defaults
      stout: true
      sterr: true
