- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/bin

- link:
    ~/bin/bat:
      force: true
      path: bin/bat-linux
    ~/bin/exa:
      force: true
      path: bin/exa-linux
    ~/.zshrc:
      force: true
      path: zsh/zshrc
    ~/.zshenv:
      force: true
      path: zsh/zshenv
    ~/.config/btop/btop.conf:
      force: true
      path: btop/btop.conf
    ~/.config/btop/themes:
      force: true
      path: btop/themes

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    -
      command: bash ./npm/set-defaults.sh
      description: Setting up sane npm defaults
      stdin: true
      stdout: true
      stderr: true
