- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/bin

- link:
    /usr/local/bin/bat:
      force: true
      path: bin/bat-linux
    /usr/local/bin/exa:
      force: true
      path: bin/exa-linux
    ~/.zshrc:
      force: true
      path: zsh/zshrc

- npm:
    - rimraf
    - npm-check

- shell:
    - [git submodule update --init --recursive, Installing submodules]
