- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/Pictures/Screenshots
    - ~/bin

- link:
    ~/bin/bat:
      force: true
      path: bin/bat-macos
    ~/bin/exa:
      force: true
      path: bin/exa-macos
    ~/.zshrc:
      force: true
      path: zsh/zshrc

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    -
      command: sh ./macos/set-defaults.sh
      description: Setting up sensible Mac defaults
      stdin: true
      stdout: true
      stderr: true
    - [sh ./macos/install-homebrew.sh, Installing and configuring Homebrew]
    -
      command: sh ./npm/set-defaults.sh
      description: Setting up sane npm defaults
      stdin: true
      stdout: true
      stderr: true
