- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/Pictures/Screenshots
    - ~/bin

- link:
    ~/.gitconfig:
      path: git/gitconfig
    ~/.git_template: git/git_template
    ~/.ssh/config:
      path: ssh/config
    ~/.vim: vim/vim
    ~/.vimrc:
      path: vim/vimrc
    ~/.zshrc:
      force: true
      path: zsh/zshrc
    ~/.zshenv:
      force: true
      path: zsh/zshenv
    ~/.config/btop/btop.conf:
      force: true
      path: btop/btop.conf
    ~/.config/btop/themes:
      force: true
      path: btop/themes

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    -
      command: bash ./macos/set-defaults.sh
      description: Setting up sensible Mac defaults
      stdin: true
      stdout: true
      stderr: true
    - [bash ./macos/install-homebrew.sh, Installing and configuring Homebrew]
    -
      command: bash ./npm/set-defaults.sh
      description: Setting up sane npm defaults
      stdin: true
      stdout: true
      stderr: true
