#!/usr/bin/env bash

set -e

CONFIG_SUFFIX=".conf.yaml"
CONFIG_DIR="meta/configs"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

echo ""
echo "Determining configuration to set up"
if [[ "$OSTYPE" == "darwin"* ]]; then
  conf="macos"
else
  conf="linux"
fi

echo ""
echo "Setting up ${conf} configuration"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG_DIR}/${conf}${CONFIG_SUFFIX}"

echo ""
echo "Restarting shell"
exec "${SHELL}" -l
