#!/usr/bin/env bash

set -e

DEFAULT_CONFIG_PREFIX="default"
CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

echo ""
echo "Running Dotbot configs"
for conf in "${DEFAULT_CONFIG_PREFIX}" "${@}"; do
  echo "Setting up ${conf} configuration"
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -p dotbot-plugins/npm.py -c "${conf}${CONFIG_SUFFIX}"
done

if [ "$#" -eq 1 ]; then
  echo ""
  echo "Changing default shell"

  zsh=$(command -v zsh)
  if ! chsh -s "$zsh"; then
      echo "ERROR ==> chsh command unsuccessful. Change your default shell manually."
    else
      export SHELL="$zsh"
      echo "Shell successfully changed to '$zsh'."
    fi
fi

echo ""
echo "Launching new shell..."
exec "$SHELL" --login
