alias grep='grep --color'
alias edit_zshrc='${EDITOR} ~/.zshrc_local'
alias edit_dotfiles_zshrc='${EDITOR} $DOTFILES/zsh/zshrc'
alias restart_zsh='clear && exec zsh -l'
alias top='vtop --theme brew'
alias oldtop='top'