#!/usr/bin/env bash

# Build test container
echo ""
echo "Building Docker container, with the whole repo as context"
docker build ../../ -f ./Dockerfile -t dotfiles-test

echo ""
echo "Build done, starting container..."
# Run test container
docker run --rm -it dotfiles-test
