source "$DOTFILES/zsh/functions/git.sh"
source "$DOTFILES/zsh/functions/exa.sh"
source "$DOTFILES/zsh/functions/misc.sh"
source "$DOTFILES/zsh/functions/docker.sh"
source "$DOTFILES/zsh/functions/history.sh"
source "$DOTFILES/zsh/functions/kubernetes.sh"
