# Path to .dotfiles
export DOTFILES="$HOME/.dotfiles"

# If you come from bash you might have to change your $PATH.
# Done fancy, because we can: https://stackoverflow.com/a/18077919/1053777
path=("$HOME/bin" "/usr/local/bin" "$DOTFILES/bin" $path)
export PATH

# Set the fpath
fpath=("$DOTFILES/zsh/fpath" $fpath)

# Initialize completion system
autoload -Uz compinit; compinit
autoload -U colors; colors

# Source my aliases, functions, options and other stuff
source "$DOTFILES/zsh/bootstrap.sh"

# Load in macOS aliases if we are on macOS, else load the Linux ones
if [[ "$OSTYPE" == "darwin"* ]]; then
    source "$DOTFILES/zsh/macos/bootstrap.sh"
else
    source "$DOTFILES/zsh/linux/bootstrap.sh"
fi

# Load themes, depending on the OS
if [[ "$OSTYPE" == "darwin"* ]]; then
    source "$DOTFILES/zsh/themes/lodybo-macos.zsh-theme"
else
    source "$DOTFILES/zsh/themes/lodybo.zsh-theme"
fi


# Load local config if it exists
if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi

# Load autocompletions on macOS
if [[ "$OSTYPE" == "darwin"* ]]; then
  source "$DOTFILES/zsh/macos/autocompletions.zsh"
fi

source "$DOTFILES/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
