# Bash config

# Path to .dotfiles
export DOTFILES="$HOME/.dotfiles"

# Set up PATH
export PATH="$DOTFILES/bin:$PATH"

# Source shell files in .dotfiles/shell
for file in "$DOTFILES/shell"
do
  source "$file"
done

# Load autocompletes
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi