# Bash config

# Path to .dotfiles
export DOTFILES="$HOME/.dotfiles"

# Set up PATH
export PATH="$DOTFILES/bin:$PATH"

# Source shell files in .dotfiles/shell
FILES="$DOTFILES/shell/*"
for file in $FILES
do
  source "$file"
done
